config/routes.rb
Rails.application.routes.draw do
  root  'home#index',               as: 'root'
  get   '/auth/google',             as: 'login'
  get   'auth/:provider/callback',  to: 'sessions#create'
  get   'logout',                   to: 'sessions#destroy'

  get   '/groups/:id/messages/new', to: 'group_messages#new',    as: 'new_group_message'
  post  '/groups/:id/messages',     to: 'group_messages#create', as: 'group_message'
  get   '/groups/:id/upload/new',   to: 'group_upload#new',      as: 'new_upload'
  post  '/groups/:id/upload',       to: 'group_upload#create',   as: 'upload'
  get   '/groups/:id/add',          to: 'add_student#new',       as: 'new_add_student'
  post  '/groups/:id/add',          to: 'add_student#create',    as: 'add_student'
  get   '/students/:id/add',        to: 'add_guardian#new',       as: 'new_add_guardian'
  post  '/students/:id/add',        to: 'add_guardian#create',    as: 'add_guardian'

  get   '/groups/:id/guardians/messages/new', to: 'group_guardians_messages#new',     as: 'new_group_guardian_message'
  post  '/groups/:id/guardians/messages',     to: 'group_guardians_messages#create',  as: 'group_guardian_message'


  resources :groups
  resources :students
  resources :messages,              only: [:new, :create]
  resources :guardians

end

app/controllers/group_guardians_messages_controller.rb
class GroupGuardiansMessagesController < ApplicationController
  before_action :current_group

  def new
    @message = current_user.messages.new
  end

  def create
    bulk_message = BulkMessage.new(@group, message_params[:body])
    bulk_message.message_guardians
    redirect_to group_path(@group)
  end

  private

    def message_params
      params.require(:message).permit(:body)
    end

    def current_group
      @group = Group.find(params[:id])
    end
end

app/views/group_guardians_messages/new.html.erb
<div class="container">
  <%= render "/shared/forms/header", header: "Message to group: #{@group.name}" %>
  <div class="row">
    <h5>Messaging guardians:</h5>
    <p class="flow-text"><%= @group.primary_guardian_names.join(", ") %></p>
  </div>

  <div class="row">
    <%= form_for @message, url: group_guardian_message_path(@group) do |f| %>
      <%= render "/shared/forms/messages", form: f %>
    <% end %>
  </div>

  <%= render 'shared/help/modal', header: "Message", text: Dialogue.new_message_help  %>
</div>