config/routes.rb
Rails.application.routes.draw do
  root  'home#index',               as: 'root'
  get   '/auth/google',             as: 'login'
  get   'auth/:provider/callback',  to: 'sessions#create'
  get   'logout',                   to: 'sessions#destroy'

  get   '/groups/:id/messages/new', to: 'group_messages#new',    as: 'new_group_message'
  post  '/groups/:id/messages',     to: 'group_messages#create', as: 'group_message'
  get   '/groups/:id/upload/new',   to: 'group_upload#new',      as: 'new_upload'
  post  '/groups/:id/upload',       to: 'group_upload#create',   as: 'upload'
  get   '/groups/:id/add',          to: 'add_student#new',       as: 'new_add_student'
  post  '/groups/:id/add',          to: 'add_student#create',    as: 'add_student'
  get   '/students/:id/add',        to: 'add_guardian#new',       as: 'new_add_guardian'
  post  '/students/:id/add',        to: 'add_guardian#create',    as: 'add_guardian'

  get   '/groups/:id/guardians/messages/new', to: 'group_guardians_messages#new',     as: 'new_group_guardian_message'
  post  '/groups/:id/guardians/messages',     to: 'group_guardians_messages#create',  as: 'group_guardian_message'


  resources :groups
  resources :students
  resources :messages,              only: [:new, :create]
  resources :guardians

end

app/controllers/group_upload_controller.rb
class GroupUploadController < ApplicationController
  def new
    @group = current_group
  end

  def create
    group_maker = GroupMaker.new(current_group, file)
    group_maker.create_students_and_guardians
    redirect_to group_path(current_group)
  end

  private

    def current_group
      Group.find(params[:id])
    end

    def file
      params[:file]
    end
end

app/views/group_upload/new.html.erb
<div class="container">
  <%= render "/shared/forms/header", header: "Bulk Upload for #{@group.name}" %>

  <div class="row">
    <%= form_tag(upload_path(@group), multipart: true, method: "post") do %>
      <div class="file-field input-field">
        <div class="btn btn-flat waves-effect waves-light amber accent-2">
          <span>File</span>
          <input name="file" type="file" accept="csv">
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text">
        </div>
      </div>

      <div class="input-field center-align">
        <%= submit_tag "Upload", class: "btn waves-effect waves-light indigo darken-3"  %>
      </div>
    <% end %>
  </div>

  <%= render 'shared/help/modal',
      header: "Bulk Upload",
      text: Dialogue.bulk_upload_text  %>
</div>