config/routes.rb
Rails.application.routes.draw do
  root  'home#index',               as: 'root'
  get   '/auth/google',             as: 'login'
  get   'auth/:provider/callback',  to: 'sessions#create'
  get   'logout',                   to: 'sessions#destroy'

  get   '/groups/:id/messages/new', to: 'group_messages#new',    as: 'new_group_message'
  post  '/groups/:id/messages',     to: 'group_messages#create', as: 'group_message'
  get   '/groups/:id/upload/new',   to: 'group_upload#new',      as: 'new_upload'
  post  '/groups/:id/upload',       to: 'group_upload#create',   as: 'upload'
  get   '/groups/:id/add',          to: 'add_student#new',       as: 'new_add_student'
  post  '/groups/:id/add',          to: 'add_student#create',    as: 'add_student'
  get   '/students/:id/add',        to: 'add_guardian#new',       as: 'new_add_guardian'
  post  '/students/:id/add',        to: 'add_guardian#create',    as: 'add_guardian'

  get   '/groups/:id/guardians/messages/new', to: 'group_guardians_messages#new',     as: 'new_group_guardian_message'
  post  '/groups/:id/guardians/messages',     to: 'group_guardians_messages#create',  as: 'group_guardian_message'


  resources :groups
  resources :students
  resources :messages,              only: [:new, :create]
  resources :guardians

end

app/controllers/add_guardian_controller.rb
class AddGuardianController < ApplicationController
  def new
    @student = Student.find(params[:id])
  end

  def create
    guardian = Guardian.find(params[:guardian])
    guardian.update(status: :active)
    student = Student.find(params[:id])
    Guardianship.find_or_create_by(student: student, guardian: guardian)
    redirect_to student_path(student)
  end
end

app/views/add_guardian/new.html.erb
<div class="container">
  <%= render "/shared/forms/header", header: "Add Existing Guardian" %>

  <div class="row">
    <%= form_tag(add_guardian_path(@student), method: "post") do %>
      <div class="input-field">
        <%= select_tag :guardian,
            options_for_select(AddContactable.new(current_user).guardian_dropdown),
            id: "guardian-select" %>
        <%= label_tag "Add existing guardian" %>
      </div>

      <div class="input-field">
        <%= submit_tag "Add", class: "btn waves-effect waves-light indigo darken-3"  %>
      </div>
    <% end %>
  </div>

  <%= render 'shared/help/modal',
      header: "Students",
      text: Dialogue.existing_guardian_help %>
</div>